//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TatooMarket.Exception.Exceptions {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceExceptMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceExceptMessages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TatooMarket.Exception.Exceptions.ResourceExceptMessages", typeof(ResourceExceptMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Comment field must have 500 or less digits.
        /// </summary>
        internal static string COMMENT_LENGTH_GREATER_THAN_500 {
            get {
                return ResourceManager.GetString("COMMENT_LENGTH_GREATER_THAN_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This e-mail already exists.
        /// </summary>
        internal static string EMAIL_EXISTS {
            get {
                return ResourceManager.GetString("EMAIL_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email format is wrong.
        /// </summary>
        internal static string EMAIL_FORMAT {
            get {
                return ResourceManager.GetString("EMAIL_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The e-mail field can&apos;t be empty.
        /// </summary>
        internal static string EMAIL_IS_EMPTY {
            get {
                return ResourceManager.GetString("EMAIL_IS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail or password invalid.
        /// </summary>
        internal static string EMAIL_PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a File format is wrong.
        /// </summary>
        internal static string FILE_FORMAT {
            get {
                return ResourceManager.GetString("FILE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The authorization token is invaild or expired.
        /// </summary>
        internal static string INVALID_TOKEN {
            get {
                return ResourceManager.GetString("INVALID_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User cannot be anonymous if is seller.
        /// </summary>
        internal static string NO_USER_ANONYMOUS_AND_SELLER {
            get {
                return ResourceManager.GetString("NO_USER_ANONYMOUS_AND_SELLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password must have 8 or more digits.
        /// </summary>
        internal static string PASSWORD_GREATER_OR_EQUAL_EIGHT {
            get {
                return ResourceManager.GetString("PASSWORD_GREATER_OR_EQUAL_EIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password is not the same.
        /// </summary>
        internal static string REPEAT_PASSWORD_ERROR {
            get {
                return ResourceManager.GetString("REPEAT_PASSWORD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Review doesn&apos;t exists.
        /// </summary>
        internal static string REVIEW_DOESNT_EXISTS {
            get {
                return ResourceManager.GetString("REVIEW_DOESNT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Review note must be 5 or less.
        /// </summary>
        internal static string REVIEW_NOTE_GREATER_THAN_5 {
            get {
                return ResourceManager.GetString("REVIEW_NOTE_GREATER_THAN_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This studio name already exists.
        /// </summary>
        internal static string STUDIO_NAME_EXISTS {
            get {
                return ResourceManager.GetString("STUDIO_NAME_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tattoo doesn&apos;t exists.
        /// </summary>
        internal static string TATTOO_DOESNT_EXISTS {
            get {
                return ResourceManager.GetString("TATTOO_DOESNT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tattoo body placement out of enum.
        /// </summary>
        internal static string TATTOO_PLACEMENT_OUT_ENUM {
            get {
                return ResourceManager.GetString("TATTOO_PLACEMENT_OUT_ENUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tattoo size out of enum.
        /// </summary>
        internal static string TATTOO_SIZE_OUT_ENUM {
            get {
                return ResourceManager.GetString("TATTOO_SIZE_OUT_ENUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tattoo Style out of enum.
        /// </summary>
        internal static string TATTOO_STYLE_OUT_ENUM {
            get {
                return ResourceManager.GetString("TATTOO_STYLE_OUT_ENUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User already has a studio.
        /// </summary>
        internal static string USER_ALREADY_HAS_STUDIO {
            get {
                return ResourceManager.GetString("USER_ALREADY_HAS_STUDIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User doens&apos;t exists
        ///.
        /// </summary>
        internal static string USER_DOESNT_EXISTS {
            get {
                return ResourceManager.GetString("USER_DOESNT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User doesn&apos;t create a studio yet.
        /// </summary>
        internal static string USER_WITHOUT_STUDIO {
            get {
                return ResourceManager.GetString("USER_WITHOUT_STUDIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This username already exists.
        /// </summary>
        internal static string USERNAME_EXISTS {
            get {
                return ResourceManager.GetString("USERNAME_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The username field can&apos;t be empty.
        /// </summary>
        internal static string USERNAME_IS_EMPTY {
            get {
                return ResourceManager.GetString("USERNAME_IS_EMPTY", resourceCulture);
            }
        }
    }
}
